# Interactive graph

Based on the figure of Time Series of Renewable Energy Percentage in the World, we found that the difference of renewable energy consumption between developed countries and developing countries was significant, where GDP per capita could be a useful measure. Therefore, our research presented the result in an interactive format using D3, focusing on the relationship between share of renewables in energy consumption and GDP per capita for different countries/regions.

The scatter plot was designed in an interactive way to display countries in different groups. In the first graph, countries were classified into advanced economies and developing ones. By clicking on buttons below the graph, users can view the distribution of one category of countries independent of the other. Since countries of the same category are of the same color, it is straightforward to see the pattern without the need of legends.

<style>
  * {
    font-family: sans-serif;
  }
</style>

<div id="plot">
</div>

<div style="padding-left: 30px;">
  <p></p>
  <button type="button" onclick="adv_eco()">Advanced Economies</button>
  <button type="button" onclick="dev_eco()">Developing Economies</button>
</div>


<br><br/>
<br><br/>

The second scatter plot is similar to the first one, but gives a more detailed classification of countries. Most countries are divided into parts of representative economies or as a single economy. The comparison between different economies becomes more intuitive.


<div id="plot2">
</div>

<div style="padding-left: 30px;">
  <p></p>
  <button type="button" onclick="asia_pacific()">Asia Pacific</button>
  <button type="button" onclick="europe()">Europe</button>
  <button type="button" onclick="africa()">Africa</button>
  <button type="button" onclick="s_america()">Central and South Ameirca</button>
  <br><br/>
  <button type="button" onclick="eurasia()">Eurasia</button>
  <button type="button" onclick="middle_east()">Middle East</button>
  <button type="button" onclick="north_america()">North America</button>
  <button type="button" onclick="china()">China</button>
</div>



<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/plot1.js"></script>
<script src="scripts/plot2.js"></script>

<br><br/>
<br><br/>

