# Introduction

The efficiency of using traditional energy is approaching its threshold,  and may bring more costs than benefits from a macro perspective, a fact underscored by climate change challenges. Using renewable energy, such as photovoltaic and wind electricity, as a sustainable alternative to fossil fuels, is an imperative trend. 

However, from the standpoint of economics, environmental initiatives like renewable energy investment sometimes conflict with economic development, and these sustainability policies are often made or rejected depending on economic cost, posing significant financial challenges for developing and underdeveloped countries. Considering the advantages in technology and economics, it is reasonable for developed countries to take leading places in developing renewable energy. Additionally, there is a hypothesis called resource curse, although not universally accepted yet, suggests that countries or regions with rich natural resources experience slower growth due to corruption and competition over the resources. If the hypothesis is valid, the development of renewable energy in these regions should be stagnated by the overexploitation of natural resources.

To verify the hypotheses, we found the dataset on the share of modern renewables in total final energy consumption across countries from the database of the International Energy Agency. First part of the project is to show the disparity in the share of renewable energy between developed, developing, and underdeveloped countries and regions, highlighting global inequalities in renewable energy development.
The second part of the project discovers factors that influence the difference in the share of using renewable energy across different countries, including GDP per capita, infrastructure, investment in renewable energy, fossil fuel subsidy, and efficiency of using renewable energy. This analysis aims to understand the reason behind the disparity in renewable energy.
